version: '3'
services:
  covidcheckin-php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: covidcheckin-php-fpm
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - YOUR_JENKINS_WORKSPACE/code:/code
    networks:
      - covidcheckin_internal
      - reverse_proxy

  covidcheckin-nginx:
    image: nginx
    container_name: covidcheckin-nginx
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - covidcheckin-php-fpm
    volumes:
      - YOUR_JENKINS_WORKSPACE/code:/code
      - YOUR_JENKINS_WORKSPACE/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - covidcheckin_internal
      - reverse_proxy
  
networks:
  covidcheckin_internal:
    external: true
